In [14]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd


In [6]:
#dir(StandardScaler)
init_data = np.array([1,2,3,4,5])
data = init_data.reshape(-1,1)
data.shape


(5, 1)

In [7]:
scaler = StandardScaler()

In [8]:
scaler.fit(data)

StandardScaler()

In [9]:
scaler.mean_
scaler.var_

array([2.])

In [10]:
scaler.transform(data)

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [12]:
 scaler.fit_transform(data)

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

## One Hot Encoding

In [15]:
df_OHE = pd.DataFrame({'animals': ['cat', 'dog', 'cat', 'beaver', 'cat', 'beaver'], 'size': [3, 2, 3, 4, 2, 1]})
df_OHE

animals  size
0     cat     3
1     dog     2
2     cat     3
3  beaver     4
4     cat     2
5  beaver     1

In [19]:
y = pd.get_dummies(df_OHE.animals, prefix='data')
y

data_beaver  data_cat  data_dog
0            0         1         0
1            0         0         1
2            0         1         0
3            1         0         0
4            0         1         0
5            1         0         0

In [21]:
pd.concat([df_OHE.drop('animals', axis = 1), y], axis=1)

size  data_beaver  data_cat  data_dog
0     3            0         1         0
1     2            0         0         1
2     3            0         1         0
3     4            1         0         0
4     2            0         1         0
5     1            1         0         0