In [21]:
from sklearn.preprocessing import StandardScaler
import numpy as np


In [22]:
#dir(StandardScaler)
init_data = np.array([1,2,3,4,5])
data = a.reshape(-1,1)
data.shape


(5, 1)

In [23]:
scaler = StandardScaler()

In [29]:
scaler.fit(data)

StandardScaler()

In [26]:
scaler.mean_
scaler.var_

array([2.])

In [27]:
scaler.transform(data)

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [30]:
 scaler.fit_transform(z)

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])