## Linear Algebra Quiz #2

![title](./img/2_1.jpeg)

We strongly suggest working with numpy :)

In [3]:
#Do your imports here
import numpy as np 


![title](./img/2_2.png)
- Which vectors below define a plane spanned by a linear combination?

In [9]:
def plane(a,b,c):
    #returns false if the vectors don't define a plane and returns which are those vectors if true
    a = np.array(a)
    b = np.array(b)
    c = np.array(c)

    #combine these points to a matrix
    plane_matrix = np.stack((a,b,c))

    #Define lambda (eigenvalue)
    pass


# Harder exercise

a = [1,2,3]
b = [2,2,2]
c = [8,8,8]

np_a = np.array(a)
np_b = np.array(b)
np_c = np.array(c)

#print(np.stack((np_a,np_b,np_c)))




#def complete_plane(*inputs):
    
#returns the first set of vectors to complete a plane, false otherwise

[[1 2 3]
 [2 2 2]
 [8 8 8]]


![title](./img/2_3.png)
- What is the solution for a and b?

In [ ]:
# do you need a function for this? What is the most efficient way to solve it?

##Answer
#No, it has no unique solution for this particular solution

![title](./img/2_4.png)
- What is the solution for a and b?

In [ ]:
# Idem. Do you need a function for this? What is the most efficient way to solve it?

##Answer
# No, this particular problem has no solution