In [30]:
# Import the needed libraries
import numpy as np

In [34]:
#**13. Create a 10x10 array with random values and find the minimum and maximum values**

arr1 = np.random.normal(15, size=(10,10))
maxvalue = arr1.max()
minvalue = arr1.min()

print(arr1)

print(maxvalue)
print(minvalue)


[[15.35502442 14.77221948 15.02243373 14.27214527 14.9844317  16.93117707
  14.98683014 14.28060585 14.59704814 15.09006052]
 [13.70617874 16.41649121 15.11225333 14.29873817 14.7840898  17.35611652
  14.53584163 15.31313234 13.22691113 12.99415066]
 [14.14557544 15.66105001 14.61589944 14.22862345 14.34150209 14.77215034
  14.47722589 15.19410323 15.34364547 16.33421513]
 [15.59417551 17.54283377 15.54970122 15.12612726 15.19787834 15.03282295
  14.34646819 16.31127954 14.46730516 14.76374695]
 [15.48503386 14.03736516 15.18498063 13.54927197 14.70539124 14.92755768
  15.03998536 13.45998018 13.26996077 14.40458813]
 [15.82161753 13.44213869 14.51854932 14.43042799 14.57408667 13.07247819
  14.42031091 15.19034539 15.19636255 15.58484809]
 [16.8586336  14.25008792 16.11287381 15.38754723 14.54348302 15.43233415
  17.72971111 13.2560829  16.61605323 13.57273024]
 [16.50124772 13.81614414 16.58626013 13.64852619 13.44042243 14.7480185
  16.68959568 14.65394255 16.3613818  14.67870443]
 

**15. Create a 2d array with 1 on the border and 0 inside**

In [32]:
arr2=np.zeros((3,3))

print("Original Array :")
print(arr2)

arr2=np.pad(arr2,pad_width=1, mode='constant', constant_values=1)

print("Padded Array with 1 on sides")
print(arr2)

Original Array :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Padded Array with 1 on sides
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
