In [43]:
# Import the needed libraries
import numpy as np

**34. How to get all the dates corresponding to the month of July 2016**

In [44]:
print("July 2016 :")


julyarr = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(julyarr)

July 2016 :
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**42. Consider two random array A and B, check if they are equal**

In [45]:
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)

print(arr1)
print(arr2)
print('\n')
print("Are the two arrays equal?")
arrayequal = np.array_equal(arr1,arr2, equal_nan=True)
print(arrayequal)


[[0.93616497 0.01730265 0.94547859]
 [0.9720102  0.33282919 0.99125101]
 [0.68997686 0.86624624 0.71850672]]
[[0.16818201 0.22688961 0.29479794]
 [0.32692131 0.87551812 0.79656067]
 [0.85919582 0.15227016 0.33895832]]


Are the two arrays equal?
False
