In [10]:
# Import the needed libraries
import numpy as np

In [11]:
#**13. Create a 10x10 array with random values and find the minimum and maximum values**

arr1 = np.random.normal(15, size=(10,10))
maxvalue = arr1.max()
minvalue = arr1.min()

print(arr1)

print(maxvalue)
print(minvalue)


[[14.89402045 13.68906745 13.88761437 15.03871724 14.38898093 14.33626239
  15.25724322 13.42258065 15.88976564 15.68560596]
 [12.6161363  16.35431447 13.33783989 16.01387161 14.52287105 12.36613231
  15.28472069 12.51170364 15.93009268 13.96091789]
 [14.76551235 15.17392712 13.46357756 14.35329436 15.19139819 14.35843084
  15.27705934 14.94999728 15.24909331 14.31898231]
 [14.67804347 16.73257896 15.25047287 13.10834706 14.71539604 17.05155167
  14.38820582 15.2334275  16.18995856 17.15187557]
 [14.61682488 12.85138308 14.85514873 15.01114671 12.94018295 16.96455244
  14.02934762 15.1616777  15.3789903  16.53757006]
 [14.01031666 13.6741094  14.76242465 15.72823106 14.72127973 14.42327986
  15.91220036 15.47619363 15.04046912 14.15254248]
 [15.28883602 14.45606568 15.41716197 13.80639666 15.66384159 14.41538287
  15.18703654 14.12992939 15.42524683 15.48746458]
 [16.05850734 13.77735218 14.07455636 15.68930023 13.97236867 15.87061584
  16.00135629 15.69946209 13.85448673 14.75322194]


**15. Create a 2d array with 1 on the border and 0 inside**

In [12]:
arr2=np.zeros((3,3))

print("Original Array :")
print(arr2)

arr2=np.pad(arr2,pad_width=1, mode='constant', constant_values=1)

print("Padded Array with 1 on sides")
print(arr2)

Original Array :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Padded Array with 1 on sides
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
