In [37]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [38]:
#To swap the rows, simply change the Index!

arr1 = np.arange(9).reshape((3,3))
print(arr1)
print('\n')
print('rearrange row 1 to row 3, and vice versa')

arr1[[0,2]]=arr1[[2,0]]
print(arr1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


rearrange row 1 to row 3, and vice versa
[[6 7 8]
 [3 4 5]
 [0 1 2]]


**75. How to compute averages using a sliding window over an array?**

In [39]:
arr1=np.arange(20)

print(arr1)

def moving_average(a,n):
    test = np.cumsum(a, dtype=float)
    print("placeholder printing")
    print(test)
    test[n:] = test[n:]-test[:-n]
    print(test[n:])
    return test[n - 1:] / n

    

moving_average(arr1,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
placeholder for each iteration
[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.]


array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17.])