In [30]:
# Import the needed libraries
import numpy as np

In [31]:
#**13. Create a 10x10 array with random values and find the minimum and maximum values**

arr1 = np.random.normal(15, size=(10,10))
maxvalue = np.max(arr1)
minvalue = np.min(arr1)

print(arr1)

print(maxvalue)
print(minvalue)


[[13.46996385 13.91891551 15.39597138 14.01048273 14.50021929 14.36116344
  14.68204641 14.66466512 15.01095213 15.95019032]
 [16.18440429 13.92355532 15.16319091 15.4864654  14.77763783 13.67526734
  17.41539371 15.75317227 14.3001992  14.38341076]
 [13.71075578 16.38158017 13.25257989 13.41776642 16.43173374 15.15285242
  15.46345871 16.38451495 14.16591824 14.33681244]
 [15.65216812 15.30414042 15.22606265 15.89413832 16.54085244 15.5100163
  13.45656187 13.14470078 15.27094145 15.05214119]
 [17.18867445 13.32249793 14.94505649 12.78006853 14.51874171 15.30269363
  14.4841887  14.46992117 16.03346826 15.82317114]
 [15.71638959 15.25786414 14.41846868 14.56738824 16.13040907 14.98204327
  15.16111315 16.63695789 14.73083328 14.13879995]
 [17.51225713 13.55022276 13.28767605 16.27327047 14.92359335 16.5053216
  13.66967034 14.858166   14.76169185 15.08963561]
 [16.38245319 14.41117078 13.39247508 15.20336033 14.30456354 13.70404371
  15.40017007 15.38312142 13.75863467 14.6967254 ]
 [

**15. Create a 2d array with 1 on the border and 0 inside**

In [32]:
arr2=np.zeros((3,3))

print("Original Array :")
print(arr2)

arr2=np.pad(arr2,pad_width=1, mode='constant', constant_values=1)

print("Padded Array with 1 on sides")
print(arr2)

Original Array :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Padded Array with 1 on sides
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
